FROM node:14-alpine
WORKDIR /react-hooks-frontend/
COPY package.json .
RUN npn install
copy . .
EXPOSE 3000
ENTRYPOINT ["npm","start"]                                                                                                                                              ~                               
